FROM golang:1.22-alpine as builder

WORKDIR /src

# Download cosign
ARG COSIGN_VERSION=v2.2.0
RUN wget https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-arm64 -O cosign

# Make it executable
RUN chmod +x cosign


FROM alpine/git:latest
COPY --from=builder /src/cosign /usr/local/bin/cosign

ENTRYPOINT ["cosign"]